### ISSUE TITLE
hookAddTwigExtension() method deprecated

### ISSUE THREAD

**Issue by jasonmccallister** [rkingon/Craft-Plugin--Trimmer#3]
Using Craft 1.3 and my log is being hit repeatedly with the follow error:

> The “hook” prefix on the Craft\TrimmerPlugin::hookAddTwigExtension() method name has been deprecated. It should be renamed to addTwigExtension().

**Comment by rkingon** [comment]
Fixed in: cb126acf0c672e4ac1f6c944da415454c346e5fe

**Comment by rkingon** [comment]
Thanks! :)
