### ISSUE TITLE
Ellipsis

### ISSUE THREAD

**Issue by steveabraham** [rkingon/Craft-Plugin--Trimmer#4]
There seems to be an issue (not sure if it's just me or not) when trimming text containing ellipsis. The trimmed text comes out as, for example:

"standard&hellip;there's beer"

Am I doing something wrong, or is there an easy fix to this?

**Comment by steveabraham** [comment]
Doh, GitHub has formatted that out. Screen shot included:

![screen shot 2014-07-23 at 20 07 57](https://cloud.githubusercontent.com/assets/201684/3678674/b36d6102-129c-11e4-9559-0222863176dd.png)

**Comment by steveabraham** [comment]
Also, spaces between sentences appear to go missing.

![screen shot 2014-07-23 at 20 51 58](https://cloud.githubusercontent.com/assets/201684/3679311/e618ec56-12a2-11e4-8e4f-78f4d9ae0d75.png)

**Comment by steveabraham** [comment]
I'm sorry, ignore all this. Issue seems to either be client or Craft related.

**Comment by rkingon** [comment]
hm ok, was about to look into it. let me know if it comes back up i'll see what i can do
