### ISSUE TITLE
Option to keep HTML tags

### ISSUE THREAD

**Issue by owldesign** [rkingon/Craft-Plugin--Trimmer#6]
For rich text field it will remove all formation the user add in their wysiwyg editor...like bold, italic, etc..

Wonder if plugin can offer option to keep html tags.

**Comment by mikestreety** [comment]
The trouble with this is if the trim happens _during_ a bold/italic tag. What would the expected behaviour be?

**Comment by rkingon** [comment]
@owldesign, @mikestreety is correct. we strip the html on purpose
